<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <Configurations>Debug;Release;Tests</Configurations>
	  <PackageId>NonoSharp</PackageId>
	  <Version>0.1.0</Version>
	  <Description>Nonogram API for .NET featuring randomly generated puzzles, custom puzzle file saving/loading and more</Description>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <RepositoryUrl>https://github.com/GiraffeLars/NonoSharp/</RepositoryUrl>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
